# NumPy Practice

In [6]:
# Import NumPy as its abbreviation 'np'
# !pip install numpy
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
array_d1 = np.array([1, 2, 4])

# Create a 2-dimensional NumPy array using np.array()
array_d2 = np.array([[1, 2, 4], 
                     [3, 5, 0], 
                     [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
array_d3 = np.array([[[1, 2, 4], 
                      [3, 5, 0], 
                      [7, 8, 9]],
                     [[1, 0, 0], 
                      [0, 1, 0], 
                      [0, 0, 1]]])

print("array_d1 :\n", array_d1)
print("array_d2 :\n", array_d2)
print("array_d3 :\n", array_d3)
array_d3

array_d1 :
 [1 2 4]
array_d2 :
 [[1 2 4]
 [3 5 0]
 [7 8 9]]
array_d3 :
 [[[1 2 4]
  [3 5 0]
  [7 8 9]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]]


array([[[1, 2, 4],
        [3, 5, 0],
        [7, 8, 9]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

In [33]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("shape : ", array_d1.shape)
print("number of dimensions : ", array_d1.ndim)
print("data type : ", array_d1.dtype)
print("size : ", len(array_d1))
print("type : ", type(array_d1))

shape :  (3,)
number of dimensions :  1
data type :  int64
size :  3
type :  <class 'numpy.ndarray'>


In [35]:
# Attributes of 2-dimensional array
print("shape : ", array_d2.shape)
print("number of dimensions : ", array_d2.ndim)
print("data type : ", array_d2.dtype)
print("size : ", len(array_d2))
print("type : ", type(array_d2))

shape :  (3, 3)
number of dimensions :  2
data type :  int64
size :  3
type :  <class 'numpy.ndarray'>


In [34]:
# Attributes of 3-dimensional array
print("shape : ", array_d3.shape)
print("number of dimensions : ", array_d3.ndim)
print("data type : ", array_d3.dtype)
print("size : ", len(array_d3))
print("type : ", type(array_d3))

shape :  (2, 3, 3)
number of dimensions :  3
data type :  int64
size :  2
type :  <class 'numpy.ndarray'>


In [5]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
# !pip install pandas
import pandas as pd

df_d2 = pd.DataFrame(data=array_d2, columns=['col_A', 'col_B', 'col_C'])
df_d2

  Using cached pandas-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)


col_A  col_B  col_C
0      1      2      4
1      3      5      0
2      7      8      9

In [52]:
# Create an array of shape (10, 2) with only ones
arr_ones = np.ones((10, 2), dtype=int)
arr_ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [53]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros = np.zeros((7, 2, 3), dtype=float)
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
# Create an array within a range of 0 and 100 with step 3
arr_step_3 = np.arange(0, 100, 3)
arr_step_3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [65]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random_int = np.random.randint(0, 10, (7, 2))
arr_random_int

array([[4, 6],
       [0, 3],
       [3, 4],
       [9, 2],
       [3, 2],
       [6, 6],
       [5, 2]])

In [64]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_float = np.random.rand(3, 5)
arr_random_float

array([[0.21517638, 0.34998948, 0.93489664, 0.45783186, 0.69044447],
       [0.16150456, 0.63864102, 0.37649813, 0.59310989, 0.13336845],
       [0.88510488, 0.36776555, 0.44349946, 0.96200332, 0.69398706]])

In [16]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_random_seed_42 = np.random.randint(0, 10, (4, 6))
arr_random_seed_42

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Запустіть комірку вище, що станеться?

Різні чи однакові числа в масиві? Чому це так?

In [99]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rows = 3
cols = 7
arr_var = np.random.randint(1, 10, (rows, cols))

# Find the unique numbers in the array you just created
arr_var_reshaped = arr_var.reshape((rows * cols))
total = {k: 0 for k in arr_var_reshaped}

for k in arr_var_reshaped:
    total[k] = total[k] + 1

arr_var, [k for k,v in total.items() if v == 1]

(array([[7, 3, 6, 5, 5, 5, 1],
        [1, 3, 4, 5, 2, 8, 2],
        [9, 2, 9, 7, 8, 2, 7]]),
 [6, 4])

In [100]:
# Find the 0'th index of the latest array you created
arr_var[0], arr_var[0][0]

(array([7, 3, 6, 5, 5, 5, 1]), 7)

In [101]:
# Get the first 2 rows of latest array you created
arr_var[:2]

array([[7, 3, 6, 5, 5, 5, 1],
       [1, 3, 4, 5, 2, 8, 2]])

In [103]:
# Get the first 2 values of the first 2 rows of the latest array
arr_var[:2, :2]

array([[7, 3],
       [1, 3]])

In [109]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rows = 3
cols = 5
size = (rows, cols)
arr_1 = np.random.randint(0, 10, size)
arr_2 = np.ones(size, dtype=int)

arr_1, arr_2

(array([[0, 2, 5, 9, 2],
        [7, 9, 1, 8, 2],
        [4, 9, 7, 1, 5]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [110]:
# Add the two arrays together
arr_1 + arr_2

array([[ 1,  3,  6, 10,  3],
       [ 8, 10,  2,  9,  3],
       [ 5, 10,  8,  2,  6]])

In [117]:
# Create another array of ones of shape (5, 3)
# arr_5_3 = np.ones((5, 3), dtype=int)
# arr_5_3
arr_2_T = arr_2.T
arr_2_T

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [118]:
# Try add the array of ones and the other most recent array together
arr_2 + arr_2_T

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

Коли ви намагаєтесь запустити останню комірку, видає помилку. Чому це так?

Як би ви це виправили?

In [131]:
fixed = arr_2[:3, :3] + arr_2_T[:3]
print(fixed)

# Create another array of ones of shape (3, 5)
arr_ones2 = np.ones((3,5), dtype=int)
arr_ones2

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [22]:
# Subtract the new array of ones from the other most recent array


In [23]:
# Multiply the ones array with the latest array


In [24]:
# Take the latest array to the power of 2 using '**'


In [25]:
# Do the same thing with np.square()


In [26]:
# Find the mean of the latest array using np.mean()


In [27]:
# Find the maximum of the latest array using np.max()


In [28]:
# Find the minimum of the latest array using np.min()


In [29]:
# Find the standard deviation of the latest array


In [30]:
# Find the variance of the latest array


In [31]:
# Reshape the latest array to (3, 5, 1)


In [32]:
# Transpose the latest array


Що робить `transpose`?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


Це може не працювати. Як би ви це виправили?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


Що відбувається, коли ви порівнюєте масиви за допомогою `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
